In [2]:
import torch
import numpy as np
a=np.random.rand(4,3)
a

array([[0.84884266, 0.06216292, 0.56449973],
       [0.7401291 , 0.69483347, 0.9379536 ],
       [0.45346586, 0.53640454, 0.90775677],
       [0.57063211, 0.82572146, 0.97348246]])

In [3]:
b=torch.from_numpy(a)
b

tensor([[0.8488, 0.0622, 0.5645],
        [0.7401, 0.6948, 0.9380],
        [0.4535, 0.5364, 0.9078],
        [0.5706, 0.8257, 0.9735]], dtype=torch.float64)

In [4]:
b.numpy()

array([[0.84884266, 0.06216292, 0.56449973],
       [0.7401291 , 0.69483347, 0.9379536 ],
       [0.45346586, 0.53640454, 0.90775677],
       [0.57063211, 0.82572146, 0.97348246]])

In [5]:
b.mul_(2)

tensor([[1.6977, 0.1243, 1.1290],
        [1.4803, 1.3897, 1.8759],
        [0.9069, 1.0728, 1.8155],
        [1.1413, 1.6514, 1.9470]], dtype=torch.float64)

In [6]:
a

array([[1.69768532, 0.12432585, 1.12899947],
       [1.4802582 , 1.38966695, 1.8759072 ],
       [0.90693172, 1.07280908, 1.81551354],
       [1.14126423, 1.65144293, 1.94696492]])